version: '3'

services:

  mysql:
    image: mysql:8.0.36
    env_file: ./env/mysql.env
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped

  app:
    image: tcancissu/codechella:1.1
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - app

volumes:
  mysql-data: